// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerEvent is sent by EventBridge when a new file arrives in the input bucket
type TriggerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEvent) Reset() {
	*x = TriggerEvent{}
	mi := &file_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEvent) ProtoMessage() {}

func (x *TriggerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEvent.ProtoReflect.Descriptor instead.
func (*TriggerEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerEvent) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TriggerEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TriggerEvent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ProcessingEvent is sent to SNS/SQS for the processor lambda
type ProcessingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	S3Uri         string                 `protobuf:"bytes,2,opt,name=s3_uri,json=s3Uri,proto3" json:"s3_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingEvent) Reset() {
	*x = ProcessingEvent{}
	mi := &file_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingEvent) ProtoMessage() {}

func (x *ProcessingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingEvent.ProtoReflect.Descriptor instead.
func (*ProcessingEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessingEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ProcessingEvent) GetS3Uri() string {
	if x != nil {
		return x.S3Uri
	}
	return ""
}

// SageMakerEvent is sent to the SageMaker caller lambda
type SageMakerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PayloadUri    string                 `protobuf:"bytes,2,opt,name=payload_uri,json=payloadUri,proto3" json:"payload_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SageMakerEvent) Reset() {
	*x = SageMakerEvent{}
	mi := &file_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SageMakerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SageMakerEvent) ProtoMessage() {}

func (x *SageMakerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SageMakerEvent.ProtoReflect.Descriptor instead.
func (*SageMakerEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *SageMakerEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SageMakerEvent) GetPayloadUri() string {
	if x != nil {
		return x.PayloadUri
	}
	return ""
}

var File_events_v1_events_proto protoreflect.FileDescriptor

const file_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16events/v1/events.proto\x12\tevents.v1\"L\n" +
	"\fTriggerEvent\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"K\n" +
	"\x0fProcessingEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x15\n" +
	"\x06s3_uri\x18\x02 \x01(\tR\x05s3Uri\"T\n" +
	"\x0eSageMakerEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vpayload_uri\x18\x02 \x01(\tR\n" +
	"payloadUriB>Z<github.com/mskluev/test-pipeline/lambdas/pkg/proto/events/v1b\x06proto3"

var (
	file_events_v1_events_proto_rawDescOnce sync.Once
	file_events_v1_events_proto_rawDescData []byte
)

func file_events_v1_events_proto_rawDescGZIP() []byte {
	file_events_v1_events_proto_rawDescOnce.Do(func() {
		file_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)))
	})
	return file_events_v1_events_proto_rawDescData
}

var file_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_v1_events_proto_goTypes = []any{
	(*TriggerEvent)(nil),    // 0: events.v1.TriggerEvent
	(*ProcessingEvent)(nil), // 1: events.v1.ProcessingEvent
	(*SageMakerEvent)(nil),  // 2: events.v1.SageMakerEvent
}
var file_events_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_events_proto_init() }
func file_events_v1_events_proto_init() {
	if File_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_events_proto_goTypes,
		DependencyIndexes: file_events_v1_events_proto_depIdxs,
		MessageInfos:      file_events_v1_events_proto_msgTypes,
	}.Build()
	File_events_v1_events_proto = out.File
	file_events_v1_events_proto_goTypes = nil
	file_events_v1_events_proto_depIdxs = nil
}
